Adjust flags/logging.go after API change
pkg/flags/logging.go:45:43:
<snip>
featuregate.MutableFeatureGate does not implement
featuregate.MutableVersionedFeatureGate (missing method AddVersioned)

Signed-off-by: Dr. Jan-Philip Gehrcke <jgehrcke@nvidia.com>